- name: archaeologist
  victory_points: 1
  cost: 2
  total: 2
  actions:
    - cards: 1
  conditionals:
    - type: action
      value:
        skill_points: 2
      has: monkey_idol
- name: cleric_of_the_sun
  cost: 3
  total: 2
  acquire:
    - health: 1
  actions:
    - attack_points: 1
      skill_points: 2
  victory_points: 1
- name: dwarven_peddlar
  cost: 2
  total: 1
  actions:
    - coins: 2
      move_points: 1
  conditionals:
    - type: victory
      value:
        victory_points: 4
      two_of:
        - chalice
        - dragon_egg
        - monkey_idol
- name: gem_collector
  cost: 4
  total: 1
  actions:
    - clank: -2
      skill_points: 2
  victory_points: 2
- name: kobold_merchant
  cost: 3
  total: 1
  actions:
    - coins: 2
  victory_points: 1
  conditionals:
    - type: action
      value:
        skill_points: 2
      has: artifact
- name: master_burglar
  cost: 3
  total: 2
  victory_points: 2
  actions:
    - trash:
        burgle: 1
      skill_points: 2
- name: mister_whiskers
  cost: 1
  total: 1
  immediate_actions:
    - dragon_attack: true
  actions:
    - clank: -2
    - dragon_attack: true
  victory_points: 1
- name: monkey_bot_3000
  cost: 5
  total: 1
  actions:
    - clank: 3
      draw: 3
  immediate_actions:
    - dragon_attack: true
  victory_points: 1
- name: rebel_captain
  cost: 3
  total: 1
  actions:
    - skill_points: 2
  conditionals:
    - type: action
      value:
        draw: 1
      has_companion: true
  victory_points: 1
- name: invoker_of_the_ancients
  cost: 4
  total: 1
  actions:
    - clank: 1
      teleport: 1
  victory_points: 1
- name: rebel_miner
  cost: 2
  total: 1
  actions:
    - coins: 2
  conditionals:
    - type: action
      value:
        draw: 1
      has_companion: true
  victory_points: 1
- name: rebel_scout
  cost: 3
  total: 1
  actions:
    - move_points: 2
  conditionals:
    - type: action
      value:
        draw: 1
      has_companion: true
  victory_points: 1
- name: rebel_soldier
  cost: 2
  total: 1
  actions:
    - attack_points: 2
  conditionals:
    - type: action
      value:
        draw: 1
      has_companion: true
  victory_points: 1
- name: the_duke
  cost: 5
  total: 1
  actions:
    - attack_points: 2
      skill_points: 2
  conditionals:
    - type: victory
      value:
        victory: 1
      custom: for_every_5_coins_add_victory_point
- name: the_mountain_king
  cost: 6
  total: 1
  actions:
    - skill_points: 2
  conditionals:
    - type: action
      value:
        attack_points: 1
      has: crown
    - type: item
      value:
        move_points: 1
      has: crown
  victory_points: 3
- name: the_queen_of_hearts
  cost: 6
  total: 1
  actions:
    - skill_points: 3
      attack_points: 1
  conditionals:
    - type: action
      value:
        health: 1
      has: crown
  victory_points: 3
- name: treasure_hunter
  cost: 3
  total: 2
  actions:
    - skill_points: 2
      attack_points: 2
      replace_card: 1
  victory_points: 1
- name: wizard
  cost: 6
  total: 1
  actions:
    - skill_points: 3
  conditionals:
    - type: victory
      value:
        victory_points: 2
      custom: for_every_secret_tome_add_victory_point
- name: tunnel_guide
  cost: 1
  total: 2
  actions:
    - move_points: 1
      attack_points: 1
- name: apothecary
  total: 1
  cost: 3
  victory_points: 2
  actions:
    - discard: 1
      health: 1
    - discard: 1
      coins: 2
    - discard: 1
      attack_points: 3
