- name: archaeologist
  victory_points: 1
  cost: 2
  total: 2
  actions:
    - add_cards: 1
  conditionals:
    - type: item
      value:
        skill_points: 2
      logic: monkey_idol == true
- name: invoker_of_the_ancients
  cost: 4
  total: 1
  actions:
    - add_teleport: 1
      add_clank: 1
- name: master_burglar
  cost: 3
  total: 2
  victory_points: 2
  actions:
    - add_trash:
        burgle: 1
      skill_points: 2
