- name: teleporter
  cost: 4
  actions:
    - add_teleport: 1
  total: 2
- name: the_vault
  conditionals:
    - environment: depths
  cost: 3
  dragon_attack: true
  actions:
    - add_coins: 5
      add_clank: 3
  total: 1
- name: shrine
  immediate_action:
    - add_dragon_cubes: 3
  actions:
    - add_health: 1
    - add_coins: 1
  cost: 2
  total: 3
