map_1:
  - x: 0
    y: 1
  - x: 1
    y: 0
  - x: 1
    y: 2
  - x: 2
    y: 1
  - x: 2
    y: 3
    metadata:
      move: 2
  - x: 3
    y: 2
    metadata:
      move: 2
  - x: 3
    y: 4
    metadata:
      move: 2
  - x: 4
    y: 3
    metadata:
      move: 2
  - x: 5
    y: 4
  - x: 5
    y: 10
    metadata:
      locked: true
  - x: 10
    y: 5
    metadata:
      locked: true
  - x: 6
    y: 2
    metadata:
      move: 2
  - x: 6
    y: 11
    metadata:
      danger: 1
  - x: 11
    y: 6
    metadata:
      danger: 1
