- name: ruby
  total: 2
  cost: 6
  immediate_actions:
    - dragon_attack: 1
  actions:
    - draw: 1
  acquire:
    - clank: 2
  victory_points: 6
- name: dragon_eye
  total: 1
  cost: 5
  immediate_actions:
    - dragon_attack: 1
  acquire:
    - clank: 2
  conditionals:
    - type: can_buy
      is_in: depths
    - type: victory
      value:
        victory_points: 10
      has: mastery_token
  actions:
    - draw: 1
- name: diamond
  total: 1
  cost: 8
  victory_points: 8
  immediate_actions:
    - dragon_attack: 1
  actions:
    - draw: 1
  acquire:
    - clank: 2
- name: sapphire
  total: 3
  cost: 4
  immediate_actions:
    - dragon_attack: 1
  victory_points: 4
  actions:
    - draw: 1
  acquire:
    - clank: 2
- name: emerald
  total: 2
  cost: 5
  immediate_actions:
    - dragon_attack: 1
  victory_points: 5
  actions:
    - draw: 1
  acquire:
    - clank: 2
