- name: ruby
  total: 2
  cost: 6
  dragon_attack: true
  actions:
    - draw: 1
  acquire:
    clank: 2
  victory_points: 6
- name: dragon_eye
  total: 1
  cost: 5
  dragon_attack: true
  acquire:
    clank: 2
  conditionals:
    - type: environment
      logic: "depths == true"
    - type: victory
      value:
        victory_points: 10
      logic: "mastery_token == true"
  actions:
    - draw: 1
- name: diamond
  total: 1
  cost: 8
  victory_points: 8
  dragon_attack: true
  actions:
    - draw: 1
  acquire:
    clank: 2
- name: sapphire
  total: 3
  cost: 4
  dragon_attack: true
  victory_points: 4
  actions:
    - draw: 1
  acquire:
    clank: 2
- name: emerald
  total: 2
  cost: 5
  dragon_attack: true
  victory_points: 5
  actions:
    - draw: 1
  acquire:
    clank: 2
