- name: pickaxe
  cost: 4
  victory_points: 2
  actions:
    - coin: 2
      attack_points: 2
  total: 2
- name: boots_of_swiftness
  total: 1
  cost: 5
  victory_points: 2
  actions:
    - move: 3
  aquire:
    - move: 1
