- name: greater_healing
  total: 2
  action:
    - health: 2
- name: greater_skill_points
  total: 2
  action:
    - skill_points: 5
- name: greater_treasure
  total: 2
  action:
    - coins: 5
- name: chalice
  total: 3
  victory_points: 7
- name: draw_three
  total: 2
  action:
    - draw: 3
