map_1:
  - tile: -1
    tags:
      - ending
    frontend_data:
      x: -3
      y: .5
  - tile: -2
    tags:
      - ending
    frontend_data:
      x: -5
      y: .5
  - tile: -3
    tags:
      - ending
    frontend_data:
      x: -7
      y: .5
  - tile: -4
    tags:
      - ending
    frontend_data:
      x: -9
      y: .5
  - tile: 0
    tags:
      - ending
    frontend_data:
      x: 0.2
      y: .5
  - tile: 1
    frontend_data:
      x: 0.2
      y: -.56
  - tile: 2
    frontend_data:
      x: -1.68
      y: -.57
  - tile: 3
    tags:
      - minor_item
    frontend_data:
      x: -3.78
      y: -.57
  - tile: 4
    tags:
      - major_item
    frontend_data:
      x: -5.6
      y: -.48
  - tile: 5
    tags:
      - major_item
    frontend_data:
      x: -7.6
      y: -.48
  - tile: 6
    tags:
      - crystal_cave
      - major_item
    frontend_data:
      x: 0.2
      y: -1.67
  - tile: 7
    tags:
      - crystal_cave
    frontend_data:
      x: -1.53
      y: -1.9
  - tile: 8
    tags:
      - major_item
    frontend_data:
      x: -4.39
      y: -2.04
  - tile: 9
    tags:
      - crystal_cave
      - minor_item
    frontend_data:
      x: -6.3
      y: -2.05
  - tile: 10
    frontend_data:
      x: -8.6
      y: -1.92
  - tile: 11
    tags:
      - health
    frontend_data:
      x: 1.1
      y: -2.9
  - tile: 12
    tags:
      - minor_item
    frontend_data:
      x: -0.9
      y: -3.33
  - tile: 13
    tags:
      - crystal_cave
    frontend_data:
      x: -2.92
      y: -2.9
  - tile: 14
    frontend_data:
      x: -4.9
      y: -3.17
  - tile: 15
    tags:
      - minor_item
    frontend_data:
      x: -7.66
      y: -3.19
  - tile: 16
    tags:
      - depths
    frontend_data:
      x: 0.64
      y: -4.52
  - tile: 17
    tags:
      - crystal_cave
      - artifact
      - depths
    frontend_data:
      x: -2.33
      y: -4.24
    items:
      - name: artifact_crown
        victory_points: 3
        total: 1
        is_artifact: true
        on_acquire:
          increase_dragon: 1
  - tile: 18
    tags:
      - market
      - minor_item
      - depths
    frontend_data:
      x: -4.2
      y: -5.22
  - tile: 19
    tags:
      - market
      - depths
      - minor_item
    frontend_data:
      x: -5.36
      y: -5.55
  - tile: 20
    tags:
      - depths
      - artifact
    frontend_data:
      x: -6.51
      y: -4.8
    items:
      - name: artifact_mask
        victory_points: 5
        total: 1
        is_artifact: true
        on_acquire:
          increase_dragon: 1
  - tile: 21
    tags:
      - crystal_cave
      - minor_item
      - depths
    frontend_data:
      x: -8.34
      y: -4.74
  - tile: 22
    tags:
      - crystal_cave
      - artifact
      - depths
    frontend_data:
      x: -1.2
      y: -5.1
    items:
      - name: artifact_banana
        victory_points: 15
        total: 1
        is_artifact: true
        on_acquire:
          increase_dragon: 1
  - tile: 23
    tags:
      - market
      - depths
    frontend_data:
      x: -3.6
      y: -6.94
  - tile: 24
    tags:
      - market
      - artifact
      - depths
    frontend_data:
      x: -5.4
      y: -7.13
    items:
      - name: artifact_vase
        victory_points: 10
        total: 1
        is_artifact: true
        on_acquire:
          increase_dragon: 1
  - tile: 25
    tags:
      - crystal_cave
      - major_item
      - depths
    frontend_data:
      x: -6.55
      y: -6.38
  - tile: 26
    tags:
      - major_item
      - depths
    frontend_data:
      x: -8.81
      y: -6.2
  - tile: 27
    tags:
      - monkey
      - depths
    frontend_data:
      x: 1.04
      y: -2.42
      player_x: 1.81
      player_y: -5.5
    items:
      - name: monkey_idol
        victory_points: 5
        total: 1
        type: monkey
      - name: monkey_idol
        victory_points: 5
        total: 1
        type: monkey
      - name: monkey_idol
        victory_points: 5
        total: 1
        type: monkey
  - tile: 28
    tags:
      - major_item
      - depths
    frontend_data:
      x: -2.27
      y: -6.32
  - tile: 29
    tags:
      - health
      - depths
    frontend_data:
      x: -7.89
      y: -7.1
  - tile: 30
    tags:
      - depths
      - artifact
    frontend_data:
      x: -8.83
      y: -7.97
    items:
      - name: artifact_mask
        victory_points: 30
        total: 1
        is_artifact: true
        on_acquire:
          increase_dragon: 1
  - tile: 31
    tags:
      - minor_item
      - depths
    frontend_data:
      x: -1.96
      y: -7.7
  - tile: 32
    tags:
      - depths
      - artifact
    frontend_data:
      x: -3.28
      y: -8.64
    items:
      - name: artifact_shield
        victory_points: 20
        total: 1
        is_artifact: true
        on_acquire:
          increase_dragon: 1
  - tile: 33
    tags:
      - crystal_cave
      - minor_item
      - depths
    frontend_data:
      x: -5.04
      y: -8.55
  - tile: 34
    tags:
      - depths
      - artifact
    frontend_data:
      x: -6.69
      y: -8.47
    items:
      - name: artifact_staff
        victory_points: 25
        total: 1
        is_artifact: true
        on_acquire:
          increase_dragon: 1
  - tile: 35
    tags:
      - major_item
      - crystal_cave
      - depths
    frontend_data:
      x: -8.16
      y: -9.38
  - tile: 36
    tags:
      - depths
    frontend_data:
      x: 0.34
      y: -9.48
  - tile: 37
    tags:
      - major_item
      - depths
    frontend_data:
      x: -1.7
      y: -9.48
  - tile: 38
    tags:
      - health
      - depths
    frontend_data:
      x: -4.67
      y: -9.68
