map_1:
  - tile: -1
    frontend_data:
      x: 0
      y: 0
      player_x: -.5
      player_y: 0
  - tile: -2
    frontend_data:
      x: 0
      y: 0
      player_x: -.5
      player_y: 0
  - tile: -3
    frontend_data:
      x: 0
      y: 0
      player_x: -.5
      player_y: 0
  - tile: -4
    frontend_data:
      x: 0
      y: 0
      player_x: -.5
  - tile: 0
    frontend_data:
      x: 0
      y: 0.9
      player_x: -.5
      player_y: 0
  - tile: 1
    frontend_data:
      x: 0
      y: -1.7
      player_x: -.5
      player_y: -1
  - tile: 2
    frontend_data:
      x: -6
      y: -1.7
      player_x: -2.5
      player_y: -1
  - tile: 3
    tags:
      - minor_item
    frontend_data:
      x: -12
      y: -1.7
      player_x: -5
      player_y: -1
  - tile: 4
    tags:
      - major_item
    frontend_data:
      x: -17
      y: -1.7
      player_x: -7
      player_y: -1
  - tile: 5
    tags:
      - major_item
    frontend_data:
      x: -23
      y: -1.5
      player_x: -9
      player_y: -.5
  - tile: 6
    tags:
      - cave
      - major_item
    frontend_data:
      x: 0
      y: -6
      player_x: -.5
      player_y: -2
  - tile: 7
    tags:
      - cave
    frontend_data:
      x: -7
      y: -6
      player_x: -3
      player_y: -3
  - tile: 8
    tags:
      - major_item
    frontend_data:
      x: -12
      y: -6
      player_x: -5
      player_y: -3
  - tile: 9
    tags:
      - cave
      - minor_item
    frontend_data:
      x: -17
      y: -7
      player_x: -7
      player_y: -3.5
  - tile: 10
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 11
    tags:
      - health
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 12
    tags:
      - minor_item
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 13
    tags:
      - cave
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 14
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 15
    tags:
      - minor_item
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 16
    tags:
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 17
    tags:
      - cave
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 18
    tags:
      - market
      - minor_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 19
    tags:
      - market
      - minor_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 20
    tags:
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 21
    tags:
      - cave
      - minor_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 22
    tags:
      - cave
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 23
    tags:
      - market
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 24
    tags:
      - market
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 25
    tags:
      - cave
      - major_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 26
    tags:
      - major_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 27
    tags:
      - depths
    frontend_data:
      x: 0
      y: -15
      player_x: -0.5
      player_y: -5
    items:
      - name: monkey_idol_hear
        victory_points: 5
        total: 1
        type: monkey
      - name: monkey_idol_see
        victory_points: 5
        total: 1
        type: monkey
      - name: monkey_idol_speak
        victory_points: 5
        total: 1
        type: monkey
  - tile: 28
    tags:
      - major_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 29
    tags:
      - health
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 30
    tags:
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 31
    tags:
      - minor_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 32
    tags:
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 33
    tags:
      - cave
      - minor_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 34
    tags:
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 35
    tags:
      - major_item
      - cave
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 36
    tags:
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 37
    tags:
      - major_item
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
  - tile: 38
    tags:
      - health
      - depths
    frontend_data:
      x: -23
      y: -6
      player_x: -9
      player_y: -2.5
