map_1:
  - name: key
    total: 3
    victory_points: 5
    tiles:
      - 18
      - 19
      - 23
      - 24
  - name: crown
    total: 3
    victory_points: 9
    tiles:
      - 18
      - 19
      - 23
      - 24
  - name: backpack
    total: 2
    victory_points: 5
    tiles:
      - 18
      - 19
      - 23
      - 24
