- name: healing
  total: 3
  action:
    - health: 1
- name: swiftness
  total: 3
  action:
    - move_points: 1
- name: strength
  total: 3
  action:
    - attack_points: 2
- name: skill_points
  total: 3
  action:
    - skill_points: 2
- name: treasure
  total: 3
  action:
    - coins: 2
- name: magic_spring
  total: 3
  action:
    - trash_options: 1
- name: dragon_egg
  total: 3
  immediate_action:
    - increase_dragon: 1
  victory_points: 3
