- name: animated_door
  total: 2
  health: 1
  actions:
    - move_points: 1
  attack: 1
  dragon_attack: true
- name: cave_troll
  total: 1
  health: 4
  actions:
    - coin: 3
      draw: 2
  conditionals:
    - type: environment
      logic: "depths == true"
- name: kobold
  total: 2
  health: 2
  dragon_attack: true
  extra_cube: 1
  actions:
    - skill_points: 1
- name: ogre
  actions:
    - coin: 5
  health: 3
  dragon_attack: true
  total: 2
