tiles:
  ending:
    size: 60
    color: 0x264859
  default:
    size: 60
    color: 0xc1a05a
  monkey:
    size: 130
    color: 0xc1a05a
preload_images:
  background: "/images/basic.png"
config:
  height: 710
  width: 700
tagable_descriptions:
  - crystal_cave
  - health
  - depths
  - market
  - ending
player_colors:
  - red
  - blue
  - green
  - pink
  - yellow
  - teal
  - orange
  - cyan
  - violet
