tiles:
  default:
    size: 20
    color: 0xe7116c
  cave:
    size: 20
    color: 0x00a9ac
  minor_item:
    size: 20
    color: 0xe4a3b7
  major_item:
    size: 20
    color: 0xbd6826
  health:
    size: 20
    color: 0xbd6826
  market:
    size: 20
    color: 0xbd6826
preload_images:
  background: "/images/basic.png"
  player: "/images/pawn.png"
config:
  height: 710
  width: 700
