- name: explore
  total: 15
  cost: 3
  actions:
    - move_points: 1
    - skill_points: 2
- name: goblin
  total: 1
  health: 2
  actions:
    - coin: 1
- name: mercenary
  total: 15
  actions:
    - attack: 2
      skill_points: 1
  cost: 2
- name: secret_tome
  victory_points: 7
  cost: 7
  total: 12
