character:
  name: string
  victory_points: number
  cost: number
  total: number
  actions: array
  acquire: array
  conditionals: array
item_enum:
  - artifact
  - monkey_idol
  - chalice
  - dragon_egg
  - companion
  - crown
is_in:
  - depths
  - crystal_cave
custom:
  - for_every_5_coins_add_victory_point: "(coins / 5) *"
  - for_every_secret_tome_add_victory_point: "secret_tome  *"
  - for_every_clank_this_turn: clank *
  - pick_card_to_discard: "current deck"
conditionals:
  types:
    - can_buy
    - action
    - victory
    - after_action_trigger
  value: object
  has: string
  has_companion: boolean
  two_of: array
  is_in: string
  for_each: string
trash:
  - (card name)
  - any
actions:
  trash: object
  skill_points: number
  ignore_monster_path: boolean
  skip_crystal_cave: boolean
  move_points: number
  replace_card: number
  teleport_points: number
  clank: number
  discard_number: number
  draw: number
  attack_points: number
  coins: number
  other_clank: number
  dragon_attack: boolean
  spend_seven_for_two_secret_tomes: boolean
  take_secret_adjacent: boolean
