- name: burgle
  victory_points: 1
  total: 6
- name: scramble
  victory_points: 1
  actions:
    - add_move_points: 1
  total: 2
- name: sidestep
  actions:
    - add_move_points: 1
  total: 1
- name: stumble
  actions:
    - add_clank: 1
  total: 1
