- name: princess
  total: 1
  victory_points: 9
  actions:
    - removed_from_round
    - immediately_end_turn
- name: countess
  total: 1
  victory_points: 9
  conditionals:
    - play: king
    - play: prince
- name: king
  total: 1
  victory_points: 7
- name: chancellor
  total: 2
  victory_points: 6
- name: prince
  total: 2
  victory_points: 5
- name: handmaid
  total: 2
  victory_points: 4
- name: baron
  total: 2
  victory_points: 3
- name: priest
  total: 2
  victory_points: 2
- name: guard
  total: 6
  victory_points: 1
- name: spy
  total: 2
